spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smd_dev
    username: smd_dev_user
    password: smvcd
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true